NAME = libft.a

SRCS = ft_isalpha.c \
	ft_toupper.c \
	ft_isdigit.c \
	ft_tolower.c \
	ft_isalnum.c \
	ft_strchr.c \
	ft_isascii.c \
	ft_strrchr.c \
	ft_isprint.c \
	ft_strncmp.c \
	ft_strlen.c \
	ft_memchr.c \
	ft_memset.c \
	ft_memcmp.c \
	ft_bzero.c \
	ft_strnstr.c \
	ft_memcpy.c \
	ft_atoi.c \
	ft_memmove.c \
	ft_strlcpy.c \
	ft_strlcat.c \
	ft_calloc.c \
	ft_strdup.c \
	ft_substr.c \
	ft_strjoin.c \
	ft_strtrim.c \
	ft_itoa.c \
	ft_strmapi.c \
	ft_striteri.c \
	ft_putchar_fd.c \
	ft_putstr_fd.c \
	ft_putendl_fd.c \
	ft_putnbr_fd.c \
	ft_split.c \

BONUS =		ft_lstlast.c \
	    ft_lstsize.c \
	    ft_lstnew.c \
	    ft_lstadd_front.c \
	    ft_lstadd_back.c \
	    ft_lstdelone.c \
	    ft_lstclear.c \
	    ft_lstlast.c \
	    ft_lstiter.c \
	    ft_lstmap.c \

AR = ar rcs

OBJS =	$(addprefix obj/, ${SRCS:.c=.o})

BONUSOBJS	= $(addprefix obj/, ${BONUS:.c=.o})

CC =	cc

CFLAGS	=	-Wall -Wextra -Werror

obj/%.o: %.c
	@mkdir -p obj
	$(CC) $(CFLAGS) -c $< -o $@

$(NAME): ${OBJS}
	$(AR) $(NAME) ${OBJS}

all:	${NAME}

clean:
	rm -f ${OBJS} ${BONUSOBJS}

fclean:	clean
	rm -f ${NAME}
	rm -rf obj

re:	fclean all

bonus : ${OBJS} ${BONUSOBJS}
	ar rc ${NAME} ${OBJS} ${BONUSOBJS}

.PHONY: all clean fclean re